# Generated by Django 4.2.18 on 2025-01-25 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_rename_instructions_recipe_cooking_steps_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='cooking_steps',
            new_name='preparation_steps',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='ingredients',
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='recipes/'),
        ),
    ]
